name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 7.x.x
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm fmt:check
      - run: pnpm lint
      - run: pnpm type-check
      - run: pnpm build
